name: OWASP-ZAP integration 
on: [push]

jobs: 
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.google.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: |
            report_html.html
            report_json.json
          
